### ISSUE TITLE
Failed to load the status-wordcount package

### ISSUE THREAD

**Issue by jeffmcneill** [segphault/status-wordcount#10]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.10.5
**Thrown From**: [status-wordcount](https://github.com/segphault/status-wordcount) package, v0.1.0

### Stack Trace

Failed to load the status-wordcount package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/jeff/.atom/packages/status-wordcount/lib/status-wordcount-view.coffee:5:199)
    at /Users/jeff/.atom/packages/status-wordcount/lib/status-wordcount-view.coffee:10:5
    at Object.<anonymous> (/Users/jeff/.atom/packages/status-wordcount/lib/status-wordcount-view.coffee:67:5)
    at Object.<anonymous> (/Users/jeff/.atom/packages/status-wordcount/lib/status-wordcount-view.coffee:69:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jeff/.atom/packages/status-wordcount/lib/status-wordcount.coffee:4:25)
    at Object.<anonymous> (/Users/jeff/.atom/packages/status-wordcount/lib/status-wordcount.coffee:21:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:536:30)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
```

### Commands

```
  2x -0:33.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "project-quick-open",
      "project-switcher",
      "recent-projects",
      "atom-print",
      "tree-ignore",
      "open-last-project-0.3.1",
      "open-last-project",
      "meteor-snippets",
      "language-mustache",
      "bookmarks",
      "background-tips",
      "bracket-matcher",
      "command-palette",
      "deprecation-cop",
      "encoding-selector",
      "exception-reporting",
      "feedback",
      "fuzzy-finder",
      "go-to-line",
      "grammar-selector",
      "metrics",
      "welcome",
      "symbols-view",
      "release-notes",
      "markdown-table-formatter",
      "autocomplete-plus",
      "dash",
      "meteor-helper",
      "tabs-to-spaces",
      "save-session",
      "spell-check",
      "markdown-preview",
      "language-latex"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "Icon",
      "icon"
    ],
    "projectHome": "/users/jeff/desktop/Google.Drive",
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-watcher, v0.4.0
markdown-preview-plus, v2.4.0
status-wordcount, v0.1.0

# Dev
No dev packages
```

**Comment by jajaperson** [comment]
Experiencing the same issue
