### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by almereyda** [segphault/status-wordcount#5]
[Enter steps to reproduce below:]

1. Activate `status-wordcount` in the Atom version below.
2. Toggle it via the command palette and write something in a file.
3. Switch the tab, i.e. by toggling the Command Palette and going to settings.

**Atom Version**: 0.176.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [status-wordcount](https://github.com/segphault/status-wordcount) package, v0.1.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/almereyda/.atom/packages/status-wordcount/lib/status-wordcount-view.coffee:13

TypeError: undefined is not a function
  at StatusWordcountView.module.exports.StatusWordcountView.updateWordCount (/home/almereyda/.atom/packages/status-wordcount/lib/status-wordcount-view.coffee:13:20)
  at atom-workspace.<anonymous> (/home/almereyda/.atom/packages/status-wordcount/lib/status-wordcount-view.coffee:1:1)
  at atom-workspace.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:110:34)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at PaneContainerView.jQuery.fn.trigger (/usr/share/atom/resources/app/src/space-pen-extensions.js:64:23)
  at PaneContainerView.module.exports.PaneContainerView.onActivePaneItemChanged (/usr/share/atom/resources/app/src/pane-container-view.js:53:19)
  at /usr/share/atom/resources/app/src/pane-container-view.js:3:61
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app/src/pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:328:21)
  at tabs-tab.<anonymous> (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:184:24)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -4:53.8 core:confirm (atom-text-editor.editor.mini)
     -4:53.8 settings-view:open (atom-text-editor.editor)
     -4:42.8 core:confirm (atom-text-editor.editor.mini)
  5x -4:31.4 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:48.8 core:paste (atom-text-editor.editor)
     -0:44.3 editor:toggle-soft-wrap (atom-text-editor.editor)
     -0:39.4 command-palette:toggle (atom-text-editor.editor)
     -0:37.0 core:confirm (atom-text-editor.editor.mini)
     -0:37.0 settings-view:open (atom-text-editor.editor)
     -0:27.1 command-palette:toggle (atom-text-editor.editor)
     -0:23.9 core:confirm (atom-text-editor.editor.mini)
     -0:23.8 atom-word-count:toggle (atom-text-editor.editor)
     -0:21.4 editor:newline (atom-text-editor.editor)
     -0:16.4 command-palette:toggle (atom-text-editor.editor)
     -0:09.7 core:confirm (atom-text-editor.editor.mini)
     -0:09.7 status-wordcount:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "open-last-project",
      "wordcount",
      "status-wordcount",
      "textstats"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-haml, v0.15.0
language-jade, v0.3.0
minimap, v3.5.6
pretty-json, v0.3.2
project-manager, v1.15.5
status-wordcount, v0.1.0
word-count, v0.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by krmaxwell** [comment]
Occurred here as well.
